parameters:
  - name: connectedServiceName
    type: string
    default: ""
  - name: fabricServiceName
    type: string
    default: ""
  - name: fabricServicePrincipalId
    type: string
    default: ""
  - name: fabricServicePrincipalSecret
    type: string
    default: ""
  - name: fabricTenantId
    type: string
    default: ""
  - name: devOpsAgentImage
    type: string
    default: "ubuntu-latest"
  - name: devOpsManagedPoolUse
    type: boolean
    default: true
  - name: devOpsPoolName
    type: string
    default: ""
  - name: environmentName
    type: string
  - name: whatIf
    type: boolean
    default: false
  - name: deployEnabled
    type: boolean
    default: true

stages:
  - stage: Deploy_${{ parameters.environmentName }}_Infrastructure
    displayName: "[${{ parameters.environmentName }}] - Deploy Fabric Infrastructure Resources"
    jobs:
      - deployment: "fabric_infra"
        pool:
          ${{ if eq(parameters.devOpsManagedPoolUse, true) }}:
            name: ${{ parameters.devOpsPoolName }}
          ${{ if eq(parameters.devOpsManagedPoolUse, false) }}:
            vmImage: ${{ parameters.devOpsAgentImage }}
        environment: fabric-${{ parameters.environmentName }}
        #condition: and(or(eq(variables['Build.SourceBranchName'], 'main'), eq('${{ parameters.whatIf }}', 'true')), eq('${{ parameters.deployEnabled }}', 'true'))
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: sources

                - task: AzurePowerShell@5
                  displayName: "Deploy Fabric ${{ parameters.environmentName }} Capacity"
                  inputs:
                    pwsh: true
                    azureSubscription: ${{ parameters.connectedServiceName }}
                    azurePowerShellVersion: latestVersion
                    ScriptType: InlineScript
                    Inline: |
                      $environment = '${{ parameters.environmentName }}'
                      $paramFilePath = "fabric-infra/fabric-cicd-v2/parameters/necp01/weu/$environment/deployFabricCapacity.param.jsonc"
                      $templatePath = "sources/infrastructure-as-code/mainTemplates/deployFabricCapacity.bicep"

                      $deployParams = @{
                        ResourceGroupName     = "ndpl-necp01-weu-f$environment-rsg"
                        TemplateFile          = $templatePath
                        TemplateParameterFile = $paramFilePath
                      }
                      if ('${{ parameters.whatIf }}' -eq 'True') {
                        New-AzResourceGroupDeployment @deployParams -WhatIf
                      } else {
                        New-AzResourceGroupDeployment @deployParams
                      }

                - task: AzurePowerShell@5
                  displayName: "Deploy Fabric ${{ parameters.environmentName }} Key Vault"
                  enabled: false
                  inputs:
                    pwsh: true
                    azureSubscription: ${{ parameters.connectedServiceName }}
                    azurePowerShellVersion: latestVersion
                    ScriptType: InlineScript
                    Inline: |
                      $environment = '${{ parameters.environmentName }}'
                      $paramFilePath = "fabric-infra/fabric-cicd-v2/parameters/necp01/weu/$environment/deployFabricKeyVault.param.jsonc"
                      $templatePath = "sources/infrastructure-as-code/mainTemplates/deployFabricKeyVault.bicep"

                      $deployParams = @{
                        ResourceGroupName     = "ndpl-necp01-weu-f$environment-rsg"
                        TemplateFile          = $templatePath
                        TemplateParameterFile = $paramFilePath
                      }
                      if ('${{ parameters.whatIf }}' -eq 'True') {
                        New-AzResourceGroupDeployment @deployParams -WhatIf
                      } else {
                        New-AzResourceGroupDeployment @deployParams
                      }
